// Generates the must-use plugin that puts the content-review widget on a beta
// site. Kept out of server.js because it is PHP living inside a JS string, and
// because the widget's own source is a real .js file (public/review-widget.js)
// rather than another layer of quoting.
//
// Design notes that are load-bearing:
//
//  * The plugin holds NO secret. A review link is the only credential, and it is
//    validated by asking the tool, server-side. That is what makes it safe to
//    ship this file to every client repository — there is nothing in it to leak,
//    and nothing to rotate across sites.
//
//  * The token appears in the URL for exactly one request. It is redeemed on
//    `init`, exchanged for a random session id held in a transient, and the
//    browser is redirected to the clean URL. It never reaches JavaScript and
//    never lands in history.
//
//  * Nothing is printed for a visitor without a session — not the widget, not a
//    stylesheet, not a marker in the HTML. A client looking at their own beta
//    site cannot tell this file exists.
//
//  * Feedback is posted to this site, same-origin, and forwarded to the tool
//    server-side. A browser never talks to the tool, so the tool's write path is
//    not reachable from a web page at all.
"use strict";
const fs = require("fs");
const path = require("path");

const WIDGET = path.join(__dirname, "public", "review-widget.js");
const HEREDOC = "G99REVIEWJS";

// Everything up to the point where the widget's own source is printed.
const HEAD = (tool) => `<?php

/**
 * Growth99 content review — in-page feedback for content editors.
 *
 * Renders nothing at all unless the visitor arrived through a valid review link,
 * so a client viewing this beta site sees an ordinary website. Delete this file
 * to switch the feature off; nothing else references it.
 *
 * Generated by the Growth99 website-build tool. Edit there, not here.
 */

if (! defined('ABSPATH')) {
    exit;
}

define('G99_REVIEW_TOOL', '${tool}');
define('G99_REVIEW_COOKIE', 'g99_review');
define('G99_REVIEW_TTL', 7200);   // 2h; a stale session simply stops working

/**
 * Redeem ?g99r=<token>: verify it with the tool, swap it for a session cookie,
 * and redirect to the same URL without it. Runs early and always redirects, so
 * the token cannot survive into the page, the address bar or the referrer.
 */
add_action('init', 'g99_review_redeem', 1);
function g99_review_redeem()
{
    if (empty($_GET['g99r'])) {
        return;
    }
    $token = sanitize_text_field(wp_unslash($_GET['g99r']));
    $clean = remove_query_arg('g99r');

    $res = wp_remote_get(
        G99_REVIEW_TOOL . '/api/webhook/review/verify?t=' . rawurlencode($token),
        ['timeout' => 8]
    );
    if (! is_wp_error($res) && (int) wp_remote_retrieve_response_code($res) === 200) {
        $data = json_decode(wp_remote_retrieve_body($res), true);
        if (is_array($data) && ! empty($data['ok'])) {
            $sid = wp_generate_password(32, false, false);
            set_transient('g99rev_' . $sid, [
                'token'     => $token,
                'reviewer'  => isset($data['reviewer']) ? $data['reviewer'] : 'Reviewer',
                'siteId'    => isset($data['siteId']) ? $data['siteId'] : '',
                'themeSlug' => isset($data['themeSlug']) ? $data['themeSlug'] : '',
            ], G99_REVIEW_TTL);
            setcookie(G99_REVIEW_COOKIE, $sid, [
                'expires'  => time() + G99_REVIEW_TTL,
                'path'     => '/',
                'secure'   => is_ssl(),
                'httponly' => true,
                'samesite' => 'Lax',
            ]);
        }
    }

    // Redirect whether or not it worked: a bad token must not stay in the URL
    // either, and an invalid link should look like an ordinary page load.
    wp_safe_redirect($clean);
    exit;
}

/** The current review session, or null. The only gate in this file. */
function g99_review_session()
{
    if (empty($_COOKIE[G99_REVIEW_COOKIE])) {
        return null;
    }
    $sid = preg_replace('/[^A-Za-z0-9]/', '', wp_unslash($_COOKIE[G99_REVIEW_COOKIE]));
    if ($sid === '') {
        return null;
    }
    $session = get_transient('g99rev_' . $sid);

    return is_array($session) ? $session : null;
}

/**
 * Same-origin only. The session cookie is SameSite=Lax, so it is not sent on a
 * cross-site POST at all; the origin check is the second lock on the same door.
 */
function g99_review_permitted()
{
    if (g99_review_session() === null) {
        return false;
    }
    $origin = get_http_origin();

    return ! $origin || untrailingslashit($origin) === untrailingslashit(home_url());
}

add_action('rest_api_init', function () {
    register_rest_route('g99/v1', '/feedback', [
        'methods'             => 'POST',
        'permission_callback' => 'g99_review_permitted',
        'callback'            => 'g99_review_feedback',
    ]);
    register_rest_route('g99/v1', '/status', [
        'methods'             => 'GET',
        'permission_callback' => 'g99_review_permitted',
        'callback'            => 'g99_review_status',
    ]);
});

/**
 * Forward a batch to the tool, server-side, with the session's token.
 *
 * get_stylesheet() goes with it and is not decoration: several beta sites share
 * one WordPress install and differ only by which theme is active, so the tool
 * has to be able to refuse a batch whose session was minted against a different
 * theme than the one currently being served.
 */
function g99_review_feedback($request)
{
    $session = g99_review_session();
    $body    = $request->get_json_params();
    $changes = isset($body['changes']) && is_array($body['changes']) ? $body['changes'] : [];
    $notes   = isset($body['notes']) && is_array($body['notes']) ? $body['notes'] : [];
    if (! $changes && ! $notes) {
        return new WP_REST_Response(['ok' => false, 'error' => 'no changes in this batch'], 400);
    }

    // Exact text pairs. Each carries the page it was made on, so one submission
    // can span pages — a reviewer works through a site, not a single URL.
    $clean = [];
    foreach (array_slice($changes, 0, 40) as $c) {
        $original    = isset($c['original']) ? (string) $c['original'] : '';
        $replacement = isset($c['replacement']) ? (string) $c['replacement'] : '';
        if ($original !== '' && $replacement !== '' && $original !== $replacement) {
            $clean[] = [
                'original'    => $original,
                'replacement' => $replacement,
                'page'        => isset($c['page']) ? (string) $c['page'] : '/',
            ];
        }
    }

    // Design notes. Passed through with only length and shape checked: the tool
    // re-validates everything, and this plugin ships to every client repository,
    // so it must not need editing each time the annotation format grows a field.
    $cleanNotes = [];
    foreach (array_slice($notes, 0, 40) as $n) {
        $elementId = isset($n['elementId']) ? (string) $n['elementId'] : '';
        $note      = isset($n['note']) ? (string) $n['note'] : '';
        if ($elementId === '' || $note === '' || ! preg_match('/^[A-Za-z0-9_-]{4,32}$/', $elementId)) {
            continue;
        }
        $cleanNotes[] = [
            'elementId' => $elementId,
            'note'      => mb_substr($note, 0, 1000),
            'page'      => isset($n['page']) ? (string) $n['page'] : '/',
            'target'    => isset($n['target']) && is_array($n['target']) ? $n['target'] : [],
        ];
    }

    if (! $clean && ! $cleanNotes) {
        return new WP_REST_Response(['ok' => false, 'error' => 'nothing usable in this batch'], 400);
    }

    $res = wp_remote_post(G99_REVIEW_TOOL . '/api/webhook/review/feedback', [
        'timeout' => 20,
        'headers' => ['Content-Type' => 'application/json'],
        'body'    => wp_json_encode([
            'token'       => $session['token'],
            'path'        => isset($body['path']) ? (string) $body['path'] : '/',
            'url'         => isset($body['url']) ? (string) $body['url'] : home_url(),
            'activeTheme' => get_stylesheet(),
            'changes'     => $clean,
            'notes'       => $cleanNotes,
            // The widget's own retry key. Carried through untouched so the tool
            // can tell a resubmission from a second batch.
            'key'         => isset($body['key']) ? (string) $body['key'] : '',
        ]),
    ]);
    if (is_wp_error($res)) {
        return new WP_REST_Response(['ok' => false, 'error' => 'could not reach the build tool'], 502);
    }

    $out = json_decode(wp_remote_retrieve_body($res), true);

    return new WP_REST_Response(
        is_array($out) ? $out : ['ok' => false, 'error' => 'unreadable reply'],
        (int) wp_remote_retrieve_response_code($res)
    );
}

/** Job progress, proxied the same way so the browser still talks only to us. */
function g99_review_status($request)
{
    $session = g99_review_session();
    $job     = (string) $request->get_param('job');
    if ($job === '') {
        return new WP_REST_Response(['ok' => false, 'error' => 'no job'], 400);
    }

    $res = wp_remote_get(G99_REVIEW_TOOL . '/api/webhook/review/status'
        . '?t=' . rawurlencode($session['token']) . '&job=' . rawurlencode($job), ['timeout' => 12]);
    if (is_wp_error($res)) {
        return new WP_REST_Response(['ok' => false, 'error' => 'could not reach the build tool'], 502);
    }
    $out = json_decode(wp_remote_retrieve_body($res), true);

    return new WP_REST_Response(is_array($out) ? $out : ['ok' => false], 200);
}

/**
 * The widget itself, printed inline for a session and for nobody else. Inline
 * rather than fetched from the tool's domain so the page makes no third-party
 * request and no client site's CSP has to be widened for us.
 */
add_action('wp_footer', 'g99_review_widget', 100);
function g99_review_widget()
{
    $session = g99_review_session();
    if ($session === null) {
        return;
    }
    $config = [
        'reviewer' => $session['reviewer'],
        'path'     => '/' . ltrim((string) parse_url(add_query_arg([]), PHP_URL_PATH), '/'),
        'rest'     => esc_url_raw(rest_url('g99/v1')),
        'nonce'    => wp_create_nonce('wp_rest'),
    ];
    echo '<script id="g99-review">window.G99_REVIEW=' . wp_json_encode($config) . ";\\n";
    echo <<<'${HEREDOC}'
`;

// Everything after it. Nowdoc, so the widget's own $ and \\ are printed verbatim.
const TAIL = `
${HEREDOC};
    echo '</' . 'script>';
}
`;

// `toolUrl` is baked in at install time: the site has to know where to verify a
// token, and a WordPress install has no way to read this deployment's env.
function reviewPluginSource(toolUrl) {
  const tool = String(toolUrl || "").replace(/\/$/, "");
  if (!/^https?:\/\//i.test(tool)) throw new Error("reviewPluginSource needs the tool's absolute public URL");
  const widget = fs.readFileSync(WIDGET, "utf8").trimEnd();
  // Both would end the script or the nowdoc early and produce a broken page.
  if (/<\/script/i.test(widget)) throw new Error("review-widget.js contains a closing script tag");
  if (widget.split("\n").some((l) => l.trimEnd() === HEREDOC + ";")) throw new Error("review-widget.js collides with the heredoc terminator");
  return HEAD(tool) + widget + TAIL;
}

module.exports = { reviewPluginSource, HEREDOC };
